# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitCloneOrg < Formula
  desc "tool to clone all repositories from a gitbub organization or user"
  homepage "https://github.com/wingmans/"
  version "0.1.5"
  license "Apache License Version 2.0"

  on_macos do
    on_intel do
      url "https://github.com/wingmans/git-clone-org/releases/download/v0.1.5/git-clone-org_Darwin_x86_64.tar.gz"
      sha256 "c2964f63a37649deaee9bbb0318bf07f609be9b2067c793cf874dcf1c74dbb30"

      def install
        bin.install "policy"
      end
    end
    on_arm do
      url "https://github.com/wingmans/git-clone-org/releases/download/v0.1.5/git-clone-org_Darwin_arm64.tar.gz"
      sha256 "51c282a83e4fe7693886352965f933f9ca8aa787e9aaf0c8d28a68dd19810be9"

      def install
        bin.install "policy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wingmans/git-clone-org/releases/download/v0.1.5/git-clone-org_Linux_x86_64.tar.gz"
        sha256 "9f96a3d7e961e46b25284a1f933d724bc39ac26196c23e2c7f1dbd71ad7f1a86"

        def install
          bin.install "policy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wingmans/git-clone-org/releases/download/v0.1.5/git-clone-org_Linux_arm64.tar.gz"
        sha256 "eea793cdcd7543a5a91d5e3210f89b31d54d57b85ff7c7ba077fcd2fcddd9b64"

        def install
          bin.install "policy"
        end
      end
    end
  end

  test do
    system "#{bin}/policy version"
  end
end
