# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitCloneOrg < Formula
  desc "policy CLI for building and managing authorization policies"
  homepage "https://github.com/wingmans/"
  version "0.1.3"
  license "Apache License Version 2.0"

  on_macos do
    on_intel do
      url "https://github.com/wingmans/git-clone-org/releases/download/v0.1.3/git-clone-org_Darwin_x86_64.tar.gz"
      sha256 "94e437d48953f34c2ecb6de26af0ffd161b820475fe80258459b0933bbf288a1"

      def install
        bin.install "policy"
      end
    end
    on_arm do
      url "https://github.com/wingmans/git-clone-org/releases/download/v0.1.3/git-clone-org_Darwin_arm64.tar.gz"
      sha256 "5ba9df8101a33343ff9beef080dbd57e1ad5668ed7349c01a69c422044b6d0db"

      def install
        bin.install "policy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wingmans/git-clone-org/releases/download/v0.1.3/git-clone-org_Linux_x86_64.tar.gz"
        sha256 "2a0d8052968c619f293e3884ed704ade2e0ec0217b827ad12bc66de6119eac62"

        def install
          bin.install "policy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wingmans/git-clone-org/releases/download/v0.1.3/git-clone-org_Linux_arm64.tar.gz"
        sha256 "eab94d383d6a1077a7c6bcf709e67c6047c394830ea7e368cadcbba8766ba183"

        def install
          bin.install "policy"
        end
      end
    end
  end

  test do
    system "#{bin}/policy version"
  end
end
