# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Policy < Formula
  desc "policy CLI for building and managing authorization policies"
  homepage "https://github.com/wingmans/"
  version "0.1.2"
  license "Apache License Version 2.0"

  on_macos do
    on_intel do
      url "https://github.com/wingmans/git-clone-org/releases/download/v0.1.2/git-clone-org_Darwin_x86_64.tar.gz"
      sha256 "f8c84daa41ef2e2100ebcfe0b8c6075f04b18d906b406d1160d37c498b684abf"

      def install
        bin.install "policy"
      end
    end
    on_arm do
      url "https://github.com/wingmans/git-clone-org/releases/download/v0.1.2/git-clone-org_Darwin_arm64.tar.gz"
      sha256 "128261ed40f1af7929ca7255259d1a8d1ade21efd9cf839303711e7b49439437"

      def install
        bin.install "policy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wingmans/git-clone-org/releases/download/v0.1.2/git-clone-org_Linux_x86_64.tar.gz"
        sha256 "6f501b97feb830a3f90d965f517f30248b81c5e2c29dfd18618071645896aad4"

        def install
          bin.install "policy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wingmans/git-clone-org/releases/download/v0.1.2/git-clone-org_Linux_arm64.tar.gz"
        sha256 "10cf0f5b31ea260ebe262b20c04bb5743d329abcc81723c0d4f5139030b24aec"

        def install
          bin.install "policy"
        end
      end
    end
  end

  test do
    system "#{bin}/policy version"
  end
end
